movieBtn = document.getElementById("movie-btn");
movieResult = document.getElementById("movie-result");
tvBtn = document.getElementById("tv-btn");
tvResult = document.getElementById("tv-result");

movies = [

    "2Fast 2Furious",
    "50 First Dates",
    "8 Mile",
    "Aladdin",
    "American Sniper",
    "Annie",
    "Annihilation",
    "Aquaman",
    "Arrival",
    "Avengers",
    "Beastly",
    "Bedtime Stories",
    "Big Daddy",
    "Blade Runner 2049",
    "Blended",
    "Bride Wars",
    "Bring It On Again",
    "Bring It On All or Nothing",
    "Burlesque",
    "Catch Me if You Can",
    "Cinderella",
    "Cinderella III",
    "Click",
    "Clueless",
    "Collection 13",
    "Crazy Rich Asians",
    "Date Night",
    "District 9",
    "Divergent",
    "Divergent: Allegiant",
    "Divergent: Insurgent",
    "Dracula Untold",
    "Ella Enchanted",
    "Elmo in Grouchland",
    "Ender's Game",
    "Ever After: A Cinderella Story",
    "Fifty Shades Darker",
    "Fifty Shades Freed",
    "Fifty Shades of Grey",
    "Flight",
    "Footloose (1984)",
    "Frozen",
    "Frozen II",
    "Ghost",
    "Ghostbusters (2016)",
    "Grease",
    "Gridiron Gang",
    "Grown Ups 2",
    "Hancock",
    "Harry Potter and the Deathly Hallows Part 1",
    "Harry Potter and the Deathly Hallows Part 2",
    "Harry Potter and the Goblet of Fire",
    "Harry Potter and the Half-Blood Prince",
    "Harry Potter and the Order of the Phoenix",
    "Harry Potter and the Philosopher's Stone",
    "Harry Potter and the Prisoner of Azkaban",
    "Heaven is for Real",
    "Home",
    "How the Grinch Stole Christmas",
    "I am Legend",
    "Inception",
    "Interstellar",
    "iRobot",
    "Iron Man",
    "Jaws",
    "Jumanji (2019)",
    "Jumper",
    "Just Go With It",
    "Knight and Day",
    "Legally Blonde",
    "Lemony Snicket's A Series of Unfortunate Events",
    "Life",
    "Maleficent",
    "Matrix",
    "Matrix: Reloaded",
    "Matrix: Revolutions",
    "Mean Girls",
    "Mr. & Mrs. Smith",
    "Mr. Deeds",
    "Never Been Kissed",
    "Norbit",
    "Open Season",
    "Paranormal 13",
    "Poltergeist",
    "Prometheus",
    "Pulp Fiction",
    "Ready Player One",
    "Rent",
    "Rio",
    "Safe Haven",
    "Save the Last Dance",
    "Scooby-Doo",
    "She's the Man",
    "Sixteen Candles",
    "Snow White",
    "Star Wars: Revenge of the Sith",
    "Stomp the Yard",
    "The 40-Year-Old Virgin",
    "The Conjuring",
    "The Fault in Our Stars",
    "The Hobbit: An Unexpected Journey",
    "The Hobbit: The Battle of the Five Armies",
    "The Hobbit: The Desolation of Smaug",
    "The Holiday",
    "The Hunger Games",
    "The Hunger Games: Catching Fire",
    "The Hunger Games: Mockingjay Part 1",
    "The Hunger Games: Mockingjay Part 2",
    "The Incredible Hulk",
    "The Internship",
    "The Last Song",
    "The Lion King 2",
    "The Lord of the Rings: The Fellowship of the Ring",
    "The Lord of the Rings: The Return of the King",
    "The Lord of the Rings: The Two Towers",
    "The Neverending Story",
    "The Notebook",
    "The Phantom of the Opera",
    "The Polar Express",
    "The Princess Bride",
    "The Scorpion King",
    "The Shallows",
    "The Vow",
    "The Wizard of Oz",
    "This Means War",
    "Thor: Ragnarok",
    "Top Gun",
    "Transformers",
    "Transformers: Dark of the Moon",
    "Transformers: Revenge of the Fallen",
    "Twilight",
    "Twilight: Breaking Dawn Part 1",
    "Twilight: Breaking Dawn Part 2",
    "Twilight: Eclipse",
    "Twilight: New Moon",
    "We Bought a Zoo",
    "Zootopia",

];

tv = [
    "Avatar: The Last Air Bender",
    "Brooklyn Nine-Nine",
    "The Office",
    "The West Wing",

];


movieBtn.addEventListener("click", function(){
    const randomMovies = Math.floor(Math.random() * movies.length);
    const selectedMovie = movies[randomMovies];

    movieResult.textContent = selectedMovie;

});

tvBtn.addEventListener("click", function(){
    const randomTv = Math.floor(Math.random() * tv.length);
    const selectedTv = tv[randomTv];

    tvResult.textContent = selectedTv;

});

